FROM rocker/shiny:4.0.5

COPY R/ui.R R/ui.R
COPY R/server.R R/server.R
COPY R/run_app.R R/run_app.R

EXPOSE 3838

ENTRYPOINT ["R", "-e", "shiny::runApp('R/run_app.R', host = '0.0.0.0', port = 3838)"]
