FROM rocker/shiny:4.0.5

RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_cran("shiny", dependencies = TRUE)'
RUN R -e 'remotes::install_cran("devtools", dependencies = TRUE)'
RUN R -e 'remotes::install_cran("cli", dependencies = TRUE)'
RUN R -e 'remotes::install_cran("memoise", dependencies = TRUE)'
RUN R -e 'remotes::install_cran("pkgbuild", dependencies = TRUE)'
RUN R -e 'remotes::install_cran("callr", dependencies = TRUE)'
RUN R -e 'remotes::install_cran("processx", dependencies = TRUE)'
RUN R -e 'remotes::install_cran("ps", dependencies = TRUE)'
RUN R -e 'remotes::install_cran("prettyunits", dependencies = TRUE)'
RUN R -e 'remotes::install_cran("pkgload", dependencies = TRUE)'
RUN R -e 'remotes::install_cran("desc", dependencies = TRUE)'
RUN R -e 'remotes::install_cran("rprojroot", dependencies = TRUE)'

# Copy what is needed for the package build
COPY DESCRIPTION r_pkg/
COPY R/pkg_app.R r_pkg/R/pkg_app.R

# Build package
WORKDIR /r_pkg
RUN R -e 'devtools::build(pkg = ".", path = ".")'
RUN cp shiny.server.app_*.tar.gz app.tar.gz
RUN R -e 'remotes::install_local("app.tar.gz")'

RUN rm shiny.server.app_*.tar.gz
EXPOSE 3838

ENTRYPOINT ["R", "-e", "shiny.server.app::pkg_app()"]
